/*
 * function to convert payload to json
 *
 */

const payloadStr = {"payload":"{\"type\":\"block_actions\",\"user\":{\"id\":\"U03T772MESH\",\"username\":\"harveykisiangani\",\"name\":\"harveykisiangani\",\"team_id\":\"T03TNQFN62V\"},\"api_app_id\":\"A08T4SJP659\",\"token\":\"cdpGCjWC3RGCqp0yCWWJa3cD\",\"container\":{\"type\":\"message\",\"message_ts\":\"1753425527.891899\",\"channel_id\":\"C08R4M9P5SM\",\"is_ephemeral\":false},\"trigger_id\":\"9252017876229.3940831754097.03c923d7e72a3cf340faef2632f37d39\",\"team\":{\"id\":\"T03TNQFN62V\",\"domain\":\"alxseco\"},\"enterprise\":null,\"is_enterprise_install\":false,\"channel\":{\"id\":\"C08R4M9P5SM\",\"name\":\"task-management\"},\"message\":{\"subtype\":\"bot_message\",\"text\":\"New Paid Time Off request from Fred Enriquez\",\"type\":\"message\",\"ts\":\"1753425527.891899\",\"bot_id\":\"B0976DMLYUU\",\"blocks\":[{\"type\":\"header\",\"block_id\":\"QZRVZ\",\"text\":{\"type\":\"plain_text\",\"text\":\"New request\",\"emoji\":true}},{\"type\":\"section\",\"block_id\":\"VDnNe\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Type:*\\nPaid Time Off\",\"verbatim\":false},{\"type\":\"mrkdwn\",\"text\":\"*Created by:*\\n<example.com|Fred Enriquez>\",\"verbatim\":false}]},{\"type\":\"section\",\"block_id\":\"zcsYJ\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*When:*\\nAug 10 - Aug 13\",\"verbatim\":false}]},{\"type\":\"actions\",\"block_id\":\"bBxhy\",\"elements\":[{\"type\":\"button\",\"action_id\":\"uSoeH\",\"text\":{\"type\":\"plain_text\",\"text\":\"Approve\",\"emoji\":true},\"style\":\"primary\",\"value\":\"click_me_123\"},{\"type\":\"button\",\"action_id\":\"Yg6CW\",\"text\":{\"type\":\"plain_text\",\"text\":\"Reject\",\"emoji\":true},\"style\":\"danger\",\"value\":\"click_me_123\"}]}]},\"state\":{\"values\":{}},\"response_url\":\"https:\\/\\/hooks.slack.com\\/actions\\/T03TNQFN62V\\/9252017836517\\/TkjfCrlsaDm022tPp3xwElcS\",\"actions\":[{\"action_id\":\"uSoeH\",\"block_id\":\"bBxhy\",\"text\":{\"type\":\"plain_text\",\"text\":\"Approve\",\"emoji\":true},\"value\":\"click_me_123\",\"style\":\"primary\",\"type\":\"button\",\"action_ts\":\"1753425537.092844\"}]}"} 


const payloadStr2 = {"payload":"{\"type\":\"block_actions\",\"user\":{\"id\":\"U03T772MESH\",\"username\":\"harveykisiangani\",\"name\":\"harveykisiangani\",\"team_id\":\"T03TNQFN62V\"},\"api_app_id\":\"A08T4SJP659\",\"token\":\"cdpGCjWC3RGCqp0yCWWJa3cD\",\"container\":{\"type\":\"message\",\"message_ts\":\"1753425527.891899\",\"channel_id\":\"C08R4M9P5SM\",\"is_ephemeral\":false},\"trigger_id\":\"9252017876229.3940831754097.03c923d7e72a3cf340faef2632f37d39\",\"team\":{\"id\":\"T03TNQFN62V\",\"domain\":\"alxseco\"},\"enterprise\":null,\"is_enterprise_install\":false,\"channel\":{\"id\":\"C08R4M9P5SM\",\"name\":\"task-management\"},\"message\":{\"subtype\":\"bot_message\",\"text\":\"New Paid Time Off request from Fred Enriquez\",\"type\":\"message\",\"ts\":\"1753425527.891899\",\"bot_id\":\"B0976DMLYUU\",\"blocks\":[{\"type\":\"header\",\"block_id\":\"QZRVZ\",\"text\":{\"type\":\"plain_text\",\"text\":\"New request\",\"emoji\":true}},{\"type\":\"section\",\"block_id\":\"VDnNe\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Type:*\\nPaid Time Off\",\"verbatim\":false},{\"type\":\"mrkdwn\",\"text\":\"*Created by:*\\n<example.com|Fred Enriquez>\",\"verbatim\":false}]},{\"type\":\"section\",\"block_id\":\"zcsYJ\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*When:*\\nAug 10 - Aug 13\",\"verbatim\":false}]},{\"type\":\"actions\",\"block_id\":\"bBxhy\",\"elements\":[{\"type\":\"button\",\"action_id\":\"uSoeH\",\"text\":{\"type\":\"plain_text\",\"text\":\"Approve\",\"emoji\":true},\"style\":\"primary\",\"value\":\"click_me_123\"},{\"type\":\"button\",\"action_id\":\"Yg6CW\",\"text\":{\"type\":\"plain_text\",\"text\":\"Reject\",\"emoji\":true},\"style\":\"danger\",\"value\":\"click_me_123\"}]}]},\"state\":{\"values\":{}},\"response_url\":\"https:\\/\\/hooks.slack.com\\/actions\\/T03TNQFN62V\\/9252017836517\\/TkjfCrlsaDm022tPp3xwElcS\",\"actions\":[{\"action_id\":\"uSoeH\",\"block_id\":\"bBxhy\",\"text\":{\"type\":\"plain_text\",\"text\":\"Approve\",\"emoji\":true},\"value\":\"click_me_123\",\"style\":\"primary\",\"type\":\"button\",\"action_ts\":\"1753425537.092844\"}]}"}
const jsonPayload = JSON.parse(payloadStr2.payload);
console.log("Payload ", jsonPayload);
console.log("Payload Message", jsonPayload.message);
