steps:
  - name: gcr.io/cloud-builders/docker
    #dir: /workspace/projectAgent-Node
    dir: projectAgent-Node
    args:
      - build
      - '-t'
      - >-
        $LOCATION-docker.pkg.dev/$PROJECT_ID/github.com/arveyk/projectagent:$COMMIT_SHA
      - '-f'
      - Dockerfile
      - '.'
  # - name: gcr.io/cloud-builders/docker
  #   args:
  #     - push
  #     - $LOCATION-docker.pkg.dev/$PROJECT_ID/github.com/arveyk/projectagent:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - approve-edit-disapprove
      - '--image'
      - $LOCATION-docker.pkg.dev/$PROJECT_ID/github.com/arveyk/projectagent:$COMMIT_SHA
      - '--region'
      - $LOCATION
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - >-
    $LOCATION-docker.pkg.dev/$PROJECT_ID/github.com/arveyk/projectagent:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
