steps:
  - name: gcr.io/cloud-builders/docker
    #dir: /workspace/projectAgent-Node
    dir: projectAgent-Node
    args:
      - build
      - '-t'
      - >-
        us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/projectagent/approve-edit-disapprove:$COMMIT_SHA
      - '-f'
      - Dockerfile
      - '.'
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/projectagent/approve-edit-disapprove:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - approve-edit-disapprove
      - '--image'
      - us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/projectagent/approve-edit-disapprove:$COMMIT_SHA
      - '--region'
      - us-west1
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - >-
    us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/projectagent/approve-edit-disapprove:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
