export const slackUsers = [
  {
    id: "USLACKBOT",
    name: "slackbot",
    is_bot: false,
    updated: 0,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "757575",
    is_email_confirmed: false,
    real_name: "Slackbot",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Slackbot",
      display_name: "Slackbot",
      avatar_hash: "sv41d8cd98f0",
      real_name_normalized: "Slackbot",
      display_name_normalized: "Slackbot",
      image_24: "https://a.slack-edge.com/80588/img/slackbot_24.png",
      image_32: "https://a.slack-edge.com/80588/img/slackbot_32.png",
      image_48: "https://a.slack-edge.com/80588/img/slackbot_48.png",
      image_72: "https://a.slack-edge.com/80588/img/slackbot_72.png",
      first_name: "slackbot",
      last_name: "",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      fields: {},
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      always_active: true,
    },
  },
  {
    id: "U08UDKY38QK",
    name: "harveyspectre",
    is_bot: false,
    updated: 1750838306,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "bc3663",
    is_email_confirmed: true,
    real_name: "Harvey Spectre",
    tz: "Africa/Nairobi",
    tz_label: "East Africa Time",
    tz_offset: 10800,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Harvey Spectre",
      display_name: "Harvey Spectre",
      avatar_hash: "398bf0d0ca2d",
      real_name_normalized: "Harvey Spectre",
      display_name_normalized: "Harvey Spectre",
      image_24:
        "sample://2d39ec5394_24.jpg",
      image_32:
        "sample://aca2d39ec5394_32.jpg",
      is_custom_image: true,
      first_name: "Harvey",
      last_name: "Spectre",
      team: "T08VADHH17S",
      email: "harveyspectre@example-mail.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
  {
    id: "U08UDKYJVBM",
    name: "james.bond",
    is_bot: false,
    updated: 1750914237,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "3c989f",
    is_email_confirmed: true,
    real_name: "James Bond (Sol)",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "James Bond (Sol)",
      display_name: "James Bond (Sol)",
      avatar_hash: "g80d6141c73d",
      real_name_normalized: "James Bond (Sol)",
      display_name_normalized: "James Bond (Sol)",
      image_24:
        "2Favatars%2Fava_0010-24.png",
      image_32:
        "Favatars%2Fava_0010-32.png",
      first_name: "James",
      last_name: "Bond (Sol)",
      team: "T08VADHH17S",
      email: "james.bond@example-domain.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
  {
    id: "U08UJBJASSZ",
    name: "project_agent_slack",
    is_bot: true,
    updated: 1748552661,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "902d59",
    is_email_confirmed: false,
    real_name: "Project Agent Slack",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Project Agent Slack",
      display_name: "",
      avatar_hash: "gad200bd696c",
      real_name_normalized: "Project Agent Slack",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0014-24.png",
      image_32:
        "Favatars%2Fava_0014-32.png",
      first_name: "Project",
      last_name: "Agent Slack",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B08UJBJA0UD",
      api_app_id: "A08UDPMPHCK",
      always_active: false,
    },
  },
  {
    id: "U08UNQC6DRS",
    name: "wf_bot_a08unqa7cg4",
    is_bot: true,
    updated: 1748631702,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: true,
    is_workflow_bot: true,
    profile: {
      real_name: "Channel icebreaker",
      display_name: "",
      avatar_hash: "50755b9f3b35",
      real_name_normalized: "Channel icebreaker",
      display_name_normalized: "",
      image_24:
        "sample:f3b355f4ff3fa_24.png",
      image_32:
        "sample:355f4ff3fa_32.png",
      is_custom_image: true,
      first_name: "Channel",
      last_name: "icebreaker",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B08UNQBFU20",
      api_app_id: "A08UNQA7CG4",
      always_active: true,
    },
  },
  {
    id: "U08VADHNG0G",
    name: "crtabitha",
    is_bot: false,
    updated: 1748550176,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "d1707d",
    is_email_confirmed: true,
    real_name: "Chimera Tabitha",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: true,
    is_owner: true,
    is_primary_owner: true,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Chimera Tabitha",
      display_name: "",
      avatar_hash: "ge03e0f52591",
      real_name_normalized: "Chimera Tabitha",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0024-24.png",
      image_32:
        "Favatars%2Fava_0024-32.png",
      first_name: "Chimera",
      last_name: "Tabitha",
      team: "T08VADHH17S",
      email: "crtabitha@example-mail.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
  {
    id: "U0928H8GAN9",
    name: "project_agent_test",
    is_bot: true,
    updated: 1750384200,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "4cc091",
    is_email_confirmed: false,
    real_name: "Project Agent Test",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Project Agent Test",
      display_name: "",
      avatar_hash: "ga6cf4263242",
      real_name_normalized: "Project Agent Test",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0015-24.png",
      image_32:
        "Favatars%2Fava_0015-32.png",
      first_name: "Project",
      last_name: "Agent Test",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B0928H8DM9T",
      api_app_id: "A0929T6JX0C",
      always_active: false,
    },
  },
  {
    id: "U092TCSFAA2",
    name: "harvey.spectre",
    is_bot: false,
    updated: 1750843038,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "a63024",
    is_email_confirmed: false,
    real_name: "Harvey Spectre",
    tz: "Africa/Nairobi",
    tz_label: "East Africa Time",
    tz_offset: 10800,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    is_invited_user: true,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Harvey Spectre",
      display_name: "",
      avatar_hash: "g80b762eddd7",
      real_name_normalized: "Harvey Spectre",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0025-24.png",
      image_32:
        "Favatars%2Fava_0025-32.png",
      first_name: "Harvey",
      last_name: "Spectre",
      team: "T08VADHH17S",
      email: "harvey.spectre@example-domain.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
  {
    id: "U092VGYVD37",
    name: "tempbot",
    is_bot: true,
    updated: 1750811987,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "8f4a2b",
    is_email_confirmed: false,
    real_name: "temp-bot",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "temp-bot",
      display_name: "",
      avatar_hash: "gee9170d1f07",
      real_name_normalized: "temp-bot",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0001-24.png",
      image_32:
        "Favatars%2Fava_0001-32.png",
      first_name: "temp-bot",
      last_name: "",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B092VGYUMBP",
      api_app_id: "A092X5J5Q0J",
      always_active: false,
    },
  },
  {
    id: "U092Y5ED78T",
    name: "n8ncloud",
    is_bot: true,
    updated: 1750918555,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "8f4a2b",
    is_email_confirmed: false,
    real_name: "n8n.cloud",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "n8n.cloud",
      display_name: "",
      avatar_hash: "596ed6fc08a5",
      real_name_normalized: "n8n.cloud",
      display_name_normalized: "",
      image_24:
        "99442_596ed6fc08a564eda6b6_24.png",
      image_32:
        "6fc08a564eda6b6_32.png",
      is_custom_image: true,
      first_name: "n8n.cloud",
      last_name: "",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B092Y5EAT4K",
      api_app_id: "A016X0AT6QL",
      always_active: false,
    },
  },
  {
    id: "U09315S1N1J",
    name: "demo_app",
    is_bot: true,
    updated: 1750856911,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "4ec0d6",
    is_email_confirmed: false,
    real_name: "Demo App",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Demo App",
      display_name: "",
      avatar_hash: "g2432c01c870",
      real_name_normalized: "Demo App",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0000-24.png",
      image_32:
        "Favatars%2Fava_0000-32.png",
      first_name: "Demo",
      last_name: "App",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B09315S12E8",
      api_app_id: "A092U8VUS30",
      always_active: false,
    },
  },
  {
    id: "U0935EFG3GD",
    name: "my_messenger",
    is_bot: true,
    updated: 1751016347,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "3c989f",
    is_email_confirmed: false,
    real_name: "My Messenger",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "My Messenger",
      display_name: "",
      avatar_hash: "g33632286aca",
      real_name_normalized: "My Messenger",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0024-24.png",
      image_32:
        "Favatars%2Fava_0024-32.png",
      first_name: "My",
      last_name: "Messenger",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B0935EFD5HB",
      api_app_id: "A0935EDQRHB",
      always_active: false,
    },
  },
  {
    id: "U093KKHP45N",
    name: "testbot",
    is_bot: true,
    updated: 1750812129,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "9e3997",
    is_email_confirmed: false,
    real_name: "test-bot",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "test-bot",
      display_name: "",
      avatar_hash: "g62d567b6b91",
      real_name_normalized: "test-bot",
      display_name_normalized: "",
      image_24:
        "Favatars%2Fava_0006-24.png",
      image_32:
        "2Favatars%2Fava_0006-32.png",
      first_name: "test-bot",
      last_name: "",
      team: "T08VADHH17S",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
      bot_id: "B093KKHP0V6",
      api_app_id: "A092RDHC78W",
      always_active: false,
    },
  },
  {
    id: "U09AE554J85",
    name: "danny.dan",
    is_bot: false,
    updated: 1755558098,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "db3150",
    is_email_confirmed: true,
    real_name: "Belteshazar",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Belteshazar",
      display_name: "Belteshazar",
      avatar_hash: "g4d5c9ca6669",
      real_name_normalized: "Belteshazar",
      display_name_normalized: "Belteshazar",
      image_24:
        "%2Favatars%2Fava_0026-24.png",
      image_32:
        "Favatars%2Fava_0026-32.png",
      first_name: "Belteshazar",
      last_name: "",
      team: "T08VADHH17S",
      email: "danny.dan@example-domain.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
  {
    id: "U09AE5RP4UV",
    name: "brooklyn",
    is_bot: false,
    updated: 1755273177,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "a72f79",
    is_email_confirmed: true,
    real_name: "Brooklyn",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Brooklyn",
      display_name: "Brooklyn",
      avatar_hash: "g2e574e7f07d",
      real_name_normalized: "Brooklyn",
      display_name_normalized: "Brooklyn",
      image_24:
        ".jpg2Favatars%2Fava_0012-24.png",
      image_32:
        "Favatars%2Fava_0012-32.png",
      first_name: "Brooklyn",
      last_name: "",
      team: "T08VADHH17S",
      email: "brooklyn@example-domain.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
  {
    id: "U09B79A2J2U",
    name: "danny.dan_1",
    is_bot: false,
    updated: 1755272344,
    is_app_user: false,
    team_id: "T08VADHH17S",
    deleted: false,
    color: "d58247",
    is_email_confirmed: true,
    real_name: "Belteshazar",
    tz: "America/Los_Angeles",
    tz_label: "Pacific Daylight Time",
    tz_offset: -25200,
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    who_can_share_contact_card: "EVERYONE",
    profile: {
      real_name: "Belteshazar",
      display_name: "Belteshazar",
      avatar_hash: "gd80bd5caa40",
      real_name_normalized: "Belteshazar",
      display_name_normalized: "Belteshazar",
      image_24:
        "avatarslack-edge.com.png",
      image_32:
        "avatar._0020-32.png",
      first_name: "Belteshazar",
      last_name: "",
      team: "T08VADHH17S",
      email: "danny.dan+1@example-domain.com",
      title: "",
      phone: "",
      skype: "",
      status_text: "",
      status_text_canonical: "",
      status_emoji: "",
      status_emoji_display_info: [],
      status_expiration: 0,
    },
  },
];

export const notionUsers = [
  {
    object: "user",
    id: "1e0d872b-594c-81e5-be86-000260493812",
    name: "Harvey Spectre",
    avatar_url: null,
    type: "person",
    person: { email: "harveyspectre@example-mail.com" },
  },
  {
    object: "user",
    id: "152d872b-594c-8145-9c2c-000204787b69",
    name: "Chimera Tabitha",
    avatar_url: null,
    type: "person",
    person: { email: "crtabitha@example-mail.com" },
  },
  {
    object: "user",
    id: "13dd872b-594c-810f-8bb4-000282e27820",
    name: "Belteshazar Bond",
    avatar_url: null,
    type: "person",
    person: { email: "danny.dan@example-domain.com" },
  },
  {
    object: "user",
    id: "1e37b3ca-5344-81aa-be14-002701d76296",
    name: "Zapier",
    avatar_url: null,
    type: "bot",
    bot: {},
  },
  {
    object: "user",
    id: "77db293e-684f-4cf7-9ea1-c915c02855a4",
    name: "all-access",
    avatar_url: null,
    type: "bot",
    bot: {
      owner: [Object],
      workspace_name: "Harvey Spectre’s Notion",
      workspace_limits: [Object],
    },
  },
  {
    object: "user",
    id: "d9eebd39-bf06-4df8-b97f-62c411a46db2",
    name: "n8n-db ",
    avatar_url: null,
    type: "bot",
    bot: {},
  },
  {
    object: "user",
    id: "7f1c15e6-a83c-4523-9623-821a091cb919",
    name: "gcloud-projectagent",
    avatar_url: null,
    type: "bot",
    bot: {},
  },
];
