import { validateDate, formatSlackDate } from "../utils/dateHandler";
import { DateTime } from "luxon";
import { Task, TaskPage } from "../utils/task";

export const createTaskInfoBlock = function (task: Task) {
  /**
   * Temporarry fix for Date format issue
   */
  // task.dueDate = new Date(task.dueDate);
  task.startDate =
    task.startDate && task.startDate.toString() !== "Invalid Date"
      ? new Date(task.startDate)
      : DateTime.now().toJSDate();
  console.log(`CreateTaskInfoBlock log message => task: ${JSON.stringify(task)}`);
  return `*Task Title:*\t\t\t${task.taskTitle} \n*Assignee:* \t\t\t${task.assignee}\n*Due Date:*\t\t\t${formatSlackDate(new Date(task.dueDate))}\n*Start Date:*\t\t\t${task.startDate !== new Date(NaN) && task.startDate !== undefined ? formatSlackDate(task.startDate) : task.startDate}\n*Phone Number:*\t${task.phoneNumber}\n*Email:*\t\t\t${task.email}\n*Preferred Channel:*\t\t\t${task.preferredChannel}\n*Description:* \t\t${task.description}\n*Project:* \t\t${task.project}`;
};

// export function createEditBlock(task: Task) {

export function createEditBlock(taskPageObj: TaskPage) {
  const task = taskPageObj.task;

  // TODO display date in user's local timezone
  let dueDate, startDate;
  dueDate = task.dueDate ? task.dueDate : "xxx";
  startDate = task.startDate ? task.startDate : "xxx";
  //  Fix for due date format different from one generated by new Date()
  task.dueDate = new Date(task.dueDate);
  return {
    blocks: [
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "*Which Field would you like to edit?*",
        },
      },
      {
        type: "divider",
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "task_title_id",
          placeholder: {
            type: "plain_text",
            text: `${task.taskTitle || "xxx"}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Task Title",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "assignee_id",
          placeholder: {
            type: "plain_text",
            text: `${task.assignee || "xxx"}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Assignee",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "due_date_id",
          placeholder: {
            type: "plain_text",
            text: `${dueDate}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Due Date",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "start_date_id",
          placeholder: {
            type: "plain_text",
            text: `${startDate}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Start Date",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "email_id",
          placeholder: {
            type: "plain_text",
            text: `${task.email || "xxx"}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Email",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "phone_number_id",
          placeholder: {
            type: "plain_text",
            text: `${task.phoneNumber || "xxx"}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Phone Number",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "preferred_channel_id",
          placeholder: {
            type: "plain_text",
            text: `${task.preferredChannel || "xxx"}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Preferred Channel",
          emoji: true,
        },
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          multiline: true,
          action_id: "description_id",
          placeholder: {
            type: "plain_text",
            text: "Please enter a value if you wish to change task details",
          },
        },
        label: {
          type: "plain_text",
          text: "Task Description",
          emoji: true,
        },
      },
      {
        type: "context",
        elements: [
          {
            type: "plain_text",
            text: `Current Task Details: ${task.description || "xxx"}`,
            emoji: true,
          },
        ],
      },
      {
        type: "input",
        element: {
          type: "plain_text_input",
          action_id: "project_id",
          placeholder: {
            type: "plain_text",
            text: `${task.project || "xxx"}`,
          },
        },
        label: {
          type: "plain_text",
          text: "Project",
          emoji: true,
        },
      },
      {
        type: "actions",
        elements: [
          {
            type: "button",
            text: {
              type: "plain_text",
              emoji: true,
              text: "Submit",
            },
            style: "primary",
            /*value: `${JSON.stringify(task)}`, */
             value: `${JSON.stringify(taskPageObj)}`,
            action_id: "actionId-0",
          },
          {
            type: "button",
            text: {
              type: "plain_text",
              emoji: true,
              text: "Discard",
            },
            style: "danger",
            value: "discard_123",
            action_id: "actionId-1",
          },
        ],
      },
      {
        type: "divider",
      },
    ],
  };
}

// export function createFinalBlock(task: Task) {
export function createFinalBlock(taskPageObj: TaskPage) {
  const task = taskPageObj.task;

  task.email ? "Ok FinalBlock" : (task.email = " ");
  task.preferredChannel ? "Ok FinalBlock" : (task.preferredChannel = "Slack");
  task.project ? "Ok FinalBlock" : (task.project = " ");
  task.phoneNumber ? "Ok FinalBlock" : (task.phoneNumber = " ");
  task.description ? "Ok FinalBlock" : (task.description = " ");
  return {
    blocks: [
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "*Please approve to apply Changes or Decline by discard*",
        },
      },
      {
        type: "divider",
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: createTaskInfoBlock(task),
        },
      },
      {
        type: "divider",
      },
      {
        type: "actions",
        elements: [
          {
            type: "button",
            text: {
              type: "plain_text",
              emoji: true,
              text: "Approve",
            },
            style: "primary",
            value: `${JSON.stringify(task)}`,  // value: `${JSON.stringify(taskPageObj)}`,
            action_id: "actionId-0",
          },
          {
            type: "button",
            text: {
              type: "plain_text",
              emoji: true,
              text: "Discard",
            },
            style: "danger",
            value: "discard_123",
            action_id: "actionId-1",
          },
          {
            type: "button",
            text: {
              type: "plain_text",
              text: "Edit",
              emoji: true,
            },
            value: JSON.stringify(task), //  value: JSON.stringify(taskPageObj),
            action_id: "actionId-2",
          },
        ],
      },
    ],
  };
}
